version: "3.8.6"

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - 3010:5000
    depends_on:
      - db

  db:
    image: mysql
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - mysql-data-beer:/var/lib/mysql
    environment:
      MYSQL_DATABASE: beer
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql-data-beer:
